ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      export PIPENV_VENV_IN_PROJECT=true;
      pipenv shell;
      pipenv install --dev;
      export FLASK_APP=src/flask_app.py;
      export FLASK_ENV=development
    command: > 
      pipenv shell;
      flask run -p 3000
